version: 2

sources: 
  - name: raw
    schema: gz_raw_data
    description: Greenweez dataset
    tables:
      - name: product
        identifier: raw_gz_product
        description: product table
      - name: sales
        identifier: raw_gz_sales
        description: sales table
      - name: ship
        identifier: raw_gz_ship
        description: shipment info table

